version: '3.8'

services:
  walmart-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8001}:${PORT:-8001}"
    env_file:
      - ./.env
    # The Dockerfile already copies the 'keys' directory but could be easier to mount as a volume for local development (e.g., to avoid rebuilding the image for key changes)
    # volumes:
    #   - ./keys:/usr/src/app/keys:ro # Mounts local ./keys to /usr/src/app/keys (read-only)
    container_name: walmart_api_service_container
